<p>This is an online portal giving a summary of updates for <a href="https://vipulnaik.com">Vipul Naik</a>. The portal code and underlying personal data are in the <a href="https://github.com/vipulnaik/daily-updates">daily-updates GitHub repository</a>. Work-related updates are in a private repository restricted to the workplace; therefore links to work-related updates will only work correctly for co-workers.</p>

<p>The data included here is purely for exploratory purposes.</p>
