create table quarter_summaries(
  year year,
  quarter int,
  notes varchar(2000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into quarter_summaries(year, quarter, notes) values
  /* 2024 */
  ('2024',1,'The highlight of this quarter was my India trip in February / March 2024, which involved a decent amount of preparatory work (some of which I had done in Q4 2023, but a bunch still needed to be done shortly before leaving). My time on day job reduced significantly while I was in India, but was moderately high for the rest of the quarter, so it averaged out to a pretty decent level.'),
  ('2024',2,'This quarter, I experienced a health scare; see https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-04-25-abdominal-pain.md for details. I also started trying to reduce my time on day job and increase the priority of server migration work, but was only partially successful, with a Portland trip in June and all the associated planning setting me back a few weeks.'),
  ('2024',3,'This quarter I was successfully able to reduce my time on day job approximately to the desired level. As it was summer time, my time on cyclic personal chores was also low. One major distraction was health issues; see https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-07-18-excessive-morning-activity-and-abdominal-pain-in-the-afternoon.md for details. Despite this, on the whole I was able to spend close to my desired amount of time on personal projects, and as a result make significant progress on my server migration work. I also spent a chunk of time on tax work but it was much more streamlined than past years.'),
  ('2024',4,'This quarter, I finished the server migration work in October, so that going forward, my personal projects time could be devoted to more directly meaningful pursuits. However, in the months of November and December, I started preparatory work for a few administrative tasks. In December I started preparing for a planned workload increase in Q1 2025, and also started looking into an India trip in 2025 to wrap up some administrative work. I also started experiencing an increase in cyclic personal chores load due to increased appetite in winter triggering an increase in the quantity of cooking, food purchases, and post-meal cleanup. For all these reasons, I did not fully get into the flow of personal projects work.'),
  /* 2025 */
  ('2025',1,'For a large part of this quarter, I temporarily increased my workload as part of a prior agreement with the company in light of temporarily reduced availability of work colleagues. Some of that increased workload bled into the weeks prior as I worked to get set up. In addition, the cyclic personal chores load was higher due to increased appetite in winter triggering an increase in the quantity of cooking, food purchases, and post-meal cleanup. As a result of all these factors, I experienced significant time squeeze, which led to my personal projects work, month change checklists, and personal finances / taxes work suffering. This was also the quarter that I started using bone conduction headphones, initially to debug hearing issues, but later continuing as an effective way to multiplex listening to videos while doing chores around the house away from the computer.'),
  ('2025',2,'The highlight of this quarter was my India trip in May/June. Preparatory work for the trip took up some of my time in April, but on the whole there was less preparatory effort needed because of the setup work I had done for my 2024 trip. I was also able to relax on the work front somewhat and get caught up with month change checklist items and finances / taxes work. I got a respiratory infection https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2025/2025-06-respiratory-infection-likely-common-cold.md after returning from India (likely caught on the flight) which slowed down some of my recovery, but nonetheless ended the quarter on a mostly caught-up note.'),
  ('2025',3,'This was an intense quarter, due to a combination of being very busy on the day job, while I also juggled a few complex administrative tasks and wrapped up my taxes. For context on how busy this quarter was at work, it was busier than any quarter since the beginning of 2024, and significantly busier than 2025 Q1 when I was officially supposed to be working more. A lot of the busyness at work was driven by changes at my workplace and my lack of calibration on whether the increased work stemming from it was one-time or represented a new normal. I erred on the side of assuming it to be one-time. Ironically, being more busy outside of work, on the complex administrative tasks, may have increased my time spent on work in two ways: (a) I kept trying to "finish off" some work stuff to free time up for the complex administrative work, which meant putting in more hours at work, and (b) I did not have enough bandwidth to strategize more broadly on how to reduce my time on work.'),
  ('2025',4,'This quarter involved gradually slowing down from the intensity of Q3. I successfully wrapped up the remainder of administrative and tax work, and continued to be uncertain about whether the day job work was something that made sense to surge on and get to a good point, versus hard-cap and spread out over a longer period. Ultimately, by early December, I decided to hard-cap going forward, but I was able to come up with a full strategy only around the end of December, to be applied in Q1 and Q2 2026. Overall, the quarter was about as busy on work as Q1 2025, so although it was quieter than Q3 2025, it was still more than my target and far from enough for me to catch up after Q3. For month change checklist items, I was approximately able to maintain the existing backlog, i.e., I did about a quarter''s worth of work in the quarter, but wasn''t able to clear the backlog. However, the planning and strategy work at the end of the quarter has put me in a good space for Q1 and Q2 2026.');
