create table quarter_summaries(
  year year,
  quarter int,
  notes varchar(3000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into quarter_summaries(year, quarter, notes) values
  /* 2024 */
  ('2024',1,'The highlight of this quarter was my India trip in February / March 2024, which involved a decent amount of preparatory work (some of which I had done in Q4 2023, but a bunch still needed to be done shortly before leaving). My time on day job reduced significantly while I was in India, but was moderately high for the rest of the quarter, so it averaged out to a pretty decent level.'),
  ('2024',2,'This quarter, I experienced a health scare; see https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-04-25-abdominal-pain.md for details. I also started trying to reduce my time on day job and increase the priority of server migration work, but was only partially successful, with a Portland trip in June and all the associated planning setting me back a few weeks.'),
  ('2024',3,'This quarter I was successfully able to reduce my time on day job approximately to the desired level. As it was summer time, my time on cyclic personal chores was also low. One major distraction was health issues; see https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-07-18-excessive-morning-activity-and-abdominal-pain-in-the-afternoon.md for details. Despite this, on the whole I was able to spend close to my desired amount of time on personal projects, and as a result make significant progress on my server migration work. I also spent a chunk of time on tax work but it was much more streamlined than past years.'),
  ('2024',4,'This quarter, I finished the server migration work in October, so that going forward, my personal projects time could be devoted to more directly meaningful pursuits. However, in the months of November and December, I started preparatory work for a few administrative tasks. In December I started preparing for a planned workload increase in Q1 2025, and also started looking into an India trip in 2025 to wrap up some administrative work. I also started experiencing an increase in cyclic personal chores load due to increased appetite in winter triggering an increase in the quantity of cooking, food purchases, and post-meal cleanup. For all these reasons, I did not fully get into the flow of personal projects work.'),
  /* 2025 */
  ('2025',1,'For a large part of this quarter, I temporarily increased my workload as part of a prior agreement with the company in light of temporarily reduced availability of work colleagues. Some of that increased workload bled into the weeks prior as I worked to get set up. In addition, the cyclic personal chores load was higher due to increased appetite in winter triggering an increase in the quantity of cooking, food purchases, and post-meal cleanup. As a result of all these factors, I experienced significant time squeeze, which led to my personal projects work, month change checklists, and personal finances / taxes work suffering. This was also the quarter that I started using bone conduction headphones, initially to debug hearing issues, but later continuing as an effective way to multiplex listening to videos while doing chores around the house away from the computer.'),
  ('2025',2,'The highlight of this quarter was my India trip in May/June. Preparatory work for the trip took up some of my time in April, but on the whole there was less preparatory effort needed because of the setup work I had done for my 2024 trip. I was also able to relax on the work front somewhat and get caught up with month change checklist items and finances / taxes work. I got a respiratory infection https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2025/2025-06-respiratory-infection-likely-common-cold.md after returning from India (likely caught on the flight) which slowed down some of my recovery, but nonetheless ended the quarter on a mostly caught-up note.'),
  ('2025',3,'This was an intense quarter, due to a combination of being very busy on the day job, while I also juggled a few complex administrative tasks and wrapped up my taxes. For context on how busy this quarter was at work, it was busier than any quarter since the beginning of 2024, and significantly busier than 2025 Q1 when I was officially supposed to be working more. A lot of the busyness at work was driven by changes at my workplace and my lack of calibration on whether the increased work stemming from it was one-time or represented a new normal. I erred on the side of assuming it to be one-time. Ironically, being more busy outside of work, on the complex administrative tasks, may have increased my time spent on work in two ways: (a) I kept trying to "finish off" some work stuff to free time up for the complex administrative work, which meant putting in more hours at work, and (b) I did not have enough bandwidth to strategize more broadly on how to reduce my time on work.'),
  ('2025',4,'This quarter involved gradually slowing down from the intensity of Q3. I successfully wrapped up the remainder of administrative and tax work, and continued to be uncertain about whether the day job work was something that made sense to surge on and get to a good point, versus hard-cap and spread out over a longer period. Ultimately, by early December, I decided to hard-cap going forward, but I was able to come up with a full strategy only around the end of December, to be applied in Q1 and Q2 2026. Overall, the quarter was about as busy on work as Q1 2025, so although it was quieter than Q3 2025, it was still more than my target and far from enough for me to catch up after Q3. For month change checklist items, I was approximately able to maintain the existing backlog, i.e., I did about a quarter''s worth of work in the quarter, but wasn''t able to clear the backlog. However, the planning and strategy work at the end of the quarter has put me in a good space for Q1 and Q2 2026.'),
  /* 2026 */
  ('2026',1,'On the day job front, this quarter was close to a normal quarter, but it wasn''t what I had hoped for it to be: a deliberately slower-than-normal quarter to facilitate me catching up on other fronts where I was backlogged. The main reason the quarter failed to be slower-than-normal was a period of a few weeks in between where I was focused on a time-sensitive work project; the average over the remaining weeks was indeed slower than normal, and close to my Q1 2026 target. I wrapped up a couple of administrative items this quarter, so I entered Q2 with no pending one-off administrative tasks. The other big change that emerged in late Q1 2026 was my increased use of Claude, but without good regulation on how to pace and time work that emerged from the many insights it provided, which itself led to me spending more time on some things than planned. In the short run, this was a negative in terms of how quickly I made progress on backlogs, though my expectation is that it''ll be a positive in the long term as I get a better handle on the time management aspect of dealing with the rapidity of insight accumulation. I was mostly on track with my taxes, with a slight backlog developed through January and February largely caught up in March, with only a bit of backlog getting into April. With other backlogs (such as balances data entry), I made moderate progress but failed to clear all the backlogs; if it hadn''t been for those intensive weeks at work in between, I likely would have cleared more of the backlogs. Specifically, (a) I stayed current on daily updates data entry, and even streamlined the process a bit, working with Claude to write a script that helped, (b) I cleared my entertainment and self-education recording backlog and kept current after that, (c) I cleared my balances data entry backlog in January (a backlog of four months) but then fell behind again, and was a month behind on data entry (with February missing) as of the end of the quarter, (d) for contractwork data entry, my backlog stayed roughly constant; I caught up on some parts of it, made progress on others, and fell behind on others, (e) I caught up with my recording backlog associated with administrative trips in the second half of 2025, and at the end of Q1 2026, the only pending items were a trip made in March 2026 and some less important stuff from Q2 2025, (f) I mostly stayed on top of the other aspects of month change checklists, with reduced compliance during the busy period of late February and early March but some retrospective catch-up in late March.');
