create table year_summaries(
  year year,
  notes varchar(2000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

insert into year_summaries(year, notes) values
  ('2014','For the first half of the year, I juggled trying out Cognito Mentoring with several part-time contract work jobs. In August, I started my first full-time job; this was at LiftIgniter. Toward the end of the year, I was discovering a work/life balance. On the personal projects front, I spent a fair amount of time editing Wikipedia and also on Open Borders: The Case blog posts.'),
  ('2015','This was a year of significant growth at my day job (LiftIgniter); the company was finding its footing. On the personal projects front, I made progress on several things that would lay the foundation for things I would be involved in for months: I discovered timelines on Wikipedia and started work on editing them; I also started farming out contract work to Issa Rice, who would be my collaborator for several years. I also started experimenting with paying Alex K. Chen for Wikipedia page creation. Most of my personal projects time was spent on Wikipedia pages and Open Borders: The Case blog posts. On a more minor note, I started contributing to wikiHow.'),
  ('2016','This was a year of continued growth at my day job (LiftIgniter). On the personal projects front, I sought more contributors to do contract work for me, and in the process I found Sebastian Sanchez, Jesse Clifton, and several others. Sebastian Sanchez would continue to be my collaborator for several years. I also switched to using git and GitHub more heavily for personal projects starting this year.'),
  ('2017','On the work front, this was the year when LiftIgniter raised its Series A, resulting in significant growth of the company and a corresponding change in my role. On the personal projects front, this was the year that I started working on the donations list website, BART, and the devec/demography data portal. My sponsored Wikipedia editing work had to leave Wikipedia, and Issa Rice set up Timelines Wiki to continue the timelines part of the work.'),
  ('2018','This was a fairly busy year with my day job at LiftIgniter; some of the reduction in my workload that had happened shortly after Series A in 2017 reversed, and there was a lot of turmoil and restructuring at the company. I didn''t get a lot of time for personal projects. I started doing daily updates GitHub issues for work and later for personal stuff this year. I had health issues toward the end of the year that were probably at least partly driven by work-related stress.'),
  ('2019','Like 2018, this was a fairly busy and stressful year at work. Efforts to offload and reduce my work did not proceed quite as expected, largely due to ongoing departures and structural changes at my workplace. I couldn''t make a lot of progress on personal projects; the kinds of personal projects work I sought to do (but didn''t get time for) was mostly related to the donations list website.'),
  ('2020','On the work front, this was the year when LiftIgniter got acquired by Maven, leading to greater relative stability in my work situation. I continued to work fairly hard for most of the year, comparable to 2018 and 2019. It was also the year when COVID hit, resulting in me switching to working from home and also resulting in more challenges with finding housemates. I did not get a lot of time for personal projects this year.'),
  ('2021','This year, my work situation started improving. Starting early in the year, I planned to reduce my time spent at work, and the reduction took effort around mid-year. By Q4 2021, I was able to spend a moderate amount of time per month on personal projects and other activities, and was able to start making headway on the donations list website.');

