create table year_summaries(
  year year,
  notes varchar(2000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into year_summaries(year, notes) values
  ('2014','For the first half of the year, I juggled trying out Cognito Mentoring with several part-time contract work jobs. In August, I started my first full-time job; this was at LiftIgniter. Toward the end of the year, I was discovering a work/life balance. On the personal projects front, I spent a fair amount of time editing Wikipedia and also on Open Borders: The Case blog posts.'),
  ('2015','This was a year of significant growth at my day job (LiftIgniter); the company was finding its footing. On the personal projects front, I made progress on several things that would lay the foundation for things I would be involved in for the several years: I discovered timelines on Wikipedia and started work on editing them; I also started farming out contract work to Issa Rice, who would be my collaborator for several years. I also started experimenting with paying Alex K. Chen for Wikipedia page creation. Most of my personal projects time was spent on Wikipedia pages and Open Borders: The Case blog posts. On a more minor note, I started contributing to wikiHow.'),
  ('2016','This was a year of continued growth at my day job (LiftIgniter). On the personal projects front, I sought more contributors to do contract work for me, and in the process I found Sebastian Sanchez, Jesse Clifton, and several others. Sebastian Sanchez would continue to be my collaborator for several years. I also switched to using git and GitHub more heavily for personal projects starting this year.'),
  ('2017','On the work front, this was the year when LiftIgniter raised its Series A, resulting in significant growth of the company and a corresponding change in my role. On the personal projects front, this was the year that I started working on the donations list website, BART, and the devec/demography data portal. My sponsored Wikipedia editing work had to leave Wikipedia, and Issa Rice set up Timelines Wiki to continue the timelines part of the work.'),
  ('2018','This was a fairly busy year with my day job at LiftIgniter; some of the reduction in my workload that had happened shortly after Series A in 2017 reversed, and there was a lot of turmoil and restructuring at the company. I didn''t get a lot of time for personal projects. I started doing daily updates GitHub issues for work and later for personal stuff this year. I had health issues toward the end of the year that were probably at least partly driven by work-related stress.'),
  ('2019','Like 2018, this was a fairly busy and stressful year at work. Efforts to offload and reduce my work did not proceed quite as expected, largely due to ongoing departures and structural changes at my workplace. I couldn''t make a lot of progress on personal projects; the kinds of personal projects work I sought to do (but didn''t get time for) was mostly related to the donations list website.'),
  ('2020','On the work front, this was the year when LiftIgniter got acquired by Maven, leading to greater relative stability in my work situation. I continued to work fairly hard for most of the year, comparable to 2018 and 2019. It was also the year when COVID hit, resulting in me switching to working from home and also resulting in more challenges with finding housemates. I did not get a lot of time for personal projects this year.'),
  ('2021','This year, my work situation started improving. Starting early in the year, I planned to reduce my time spent at work, and the reduction took effort around mid-year. By Q4 2021, I was able to spend a moderate amount of time per month on personal projects and other activities, and was able to start making headway on the donations list website.'),
  ('2022','This was a year of change: I switched jobs and also moved to a new house. The period from February till around October of this year included a lot of work related to these switches as well as other changes I made along with the switches, including work on the streamlining of personal practices. As a result, I didn''t make as much progress on personal projects as I had hoped, and may not be able to make much progress even in early 2023 as I am still adjusting to the new job.'),
  ('2023','This was a year of change: after things didn''t work out at Equator, and I returned to Arena (the new name of Maven) in March, albeit now just in a half-time capacity, in order to free up my time for other things. I spent the year doing a bunch of complex and long-pending tasks, some of which I list here. On the personal projects front: server migration including Google Analytics migration (most of the work around June). On the personal finances, income and taxes front: a lot of cleanup, streamlining, and automation around personal finances, income and taxes, including handling a relatively complex 2022 for taxes (most of the work around August, with some work from July to October). On the personal chores front: wisdom tooth removal (July and August), a bunch of stuff related to India trip planning (September to December), and work on my health profile and contingency planning (October and November). On the career and family planning front: start putting together some notes (December). Combine these with the fact that it took me until the end of May to wrap up Equator work (despite leaving in early March) and get enough of a grip on Arena work to be properly half-time, and basically I did not get as much time in 2023 for open-ended work on personal projects. My expectation as of the end of 2023 is that 2024 will be much more focused on personal projects, especially after the first quarter (that includes the India trip), and after the second quarter it should be more focused on open-ended personal projects as the server migration should be completed by then.'),
  ('2024','After significant change in the past two years, this was a year of relative stability on the job front: I worked half-time at Arena for the whole year. However, it was busy in a number of other respects compared to previous years: I traveled to India after over 6 years, a process that required more planning because of the long gap (some of that planning had already happened in 2023, but a lot needed to be done in 2024). I finishing a long-pending Linode server migration, wrapped up various tax complications, dealt with a bunch of GI issues, and ramped up my general efforts to learn about health and get on top of my own health. In late November and early December, I was able to "live the dream" ramping up personal projects and starting to get back in the creative flow. Unfortunately, a few complications made me switch gears in the last few weeks of 2024: administrative issues, identification of some long-term health things that need more ongoing action, and anticipation of a busy Q1 2025 for reasons outside of my control.'),
  ('2025','While pretty stable at a macro level, this year was a year of many detours, though I ended the year with a moderate level of control and a strategy for the future. The detours include: a planned temporary increase in workload in Q1 2025, an India trip (with administrative tasks) in Q2 2025, complex administrative tasks in Q3 2025, and adjusting my day job responsibilities to technology changes at the company after they initially generated large amounts of work for me (this was throughout the year but peaked in Q3 2025, with residual effects in Q4 2025). The net effect of these is an increase in time per week in the day job and personal chores buckets. I also more efficiently multiplexed my time doing chores around the house with listening to educational content, thanks to bone conduction headphones. This did increase my time in the other activities bucket, and my total accounted-for time, but it might have slightly reduced my energy level and focus for the time I was on the computer -- the effect size if any is unclear. As a result of all these factors (particularly the day job and personal chores buckets) my time in the personal projects bucket dropped significantly, from about 3 hours per week in 2024 to about 30 minutes per week in 2025.');
